version: "3.8"

services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: market-db
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
volumes:
    db:
